package modelo;
// Generated Jan 29, 2025, 10:03:18 AM by Hibernate Tools 6.5.1.Final

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlTransient;

/**
 * Empleado generated by hbm2java
 */

@XmlAccessorType(XmlAccessType.NONE)
public class Empleado implements java.io.Serializable {

	private String dni;
	
	private Departamento departamento;
	private String nomEmp;
	private EmpleadoDatosProf empleadoDatosProf;

	public Empleado() {
	}

	public Empleado(String dni, Departamento departamento, String nomEmp) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, Departamento departamento, String nomEmp, EmpleadoDatosProf empleadoDatosProf) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
		this.empleadoDatosProf = empleadoDatosProf;
	}

	@XmlElement(name = "dni")
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@XmlTransient
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@XmlElement(name = "nombre")
	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public EmpleadoDatosProf getEmpleadoDatosProf() {
		return this.empleadoDatosProf;
	}

	public void setEmpleadoDatosProf(EmpleadoDatosProf empleadoDatosProf) {
		this.empleadoDatosProf = empleadoDatosProf;
	}

}
