package modelo;
// Generated Jan 29, 2025, 10:03:18 AM by Hibernate Tools 6.5.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Date FInicio;
	private Date FFin;
	private String nomProy;
	private Set<ProyectoSede> proyectoSedes = new HashSet<>(0);
	
	public Proyecto() {
		super();
	}

	public Proyecto(java.util.Date fechaInicio, java.util.Date fechaFin, String nombre) {
		this.FInicio = fechaInicio;
		this.FFin = fechaFin;
		this.nomProy = nombre;
	}

	public Proyecto(Date FInicio, String nomProy) {
		this.FInicio = FInicio;
		this.nomProy = nomProy;
	}

	public Proyecto(Date FInicio, Date FFin, String nomProy, Set<ProyectoSede> proyectoSedes) {
		this.FInicio = FInicio;
		this.FFin = FFin;
		this.nomProy = nomProy;
		this.proyectoSedes = proyectoSedes;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Date getFInicio() {
		return this.FInicio;
	}

	public void setFInicio(Date FInicio) {
		this.FInicio = FInicio;
	}

	public Date getFFin() {
		return this.FFin;
	}

	public void setFFin(Date FFin) {
		this.FFin = FFin;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set<ProyectoSede> getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

}
