package modelo;
// Generated Jan 29, 2025, 10:03:18 AM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlTransient;

/**
 * Sede generated by hbm2java
 */

@XmlAccessorType(XmlAccessType.NONE)
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSede;
	private String nomSede;
	private Set<Departamento> departamentos = new HashSet<>(0);
	private Set<ProyectoSede> proyectoSedes = new HashSet<>(0);

	public Sede() {
	}

	public Sede(int idSede, String nomSede) {
		this.idSede = idSede;
		this.nomSede = nomSede;
	}

	public Sede(int idSede, String nomSede, Set<Departamento> departamentos, Set<ProyectoSede> proyectoSedes) {
		this.idSede = idSede;
		this.nomSede = nomSede;
		this.departamentos = departamentos;
		this.proyectoSedes = proyectoSedes;
	}

	@XmlElement(name = "id_sede")
	public int getIdSede() {
		return this.idSede;
	}

	public void setIdSede(int idSede) {
		this.idSede = idSede;
	}

	 @XmlElement(name = "nombre")
	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	@XmlTransient
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	public Set<ProyectoSede> getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

	@Override
	public String toString() {
		return "Sede: idSede=" + idSede + ", nomSede=" + nomSede;
	}

	
}
