package modelo;
// Generated Jan 29, 2025, 10:03:18 AM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSede;
	private String nomSede;
	private Set<Departamento> departamentos = new HashSet<>(0);
	private Set<ProyectoSede> proyectoSedes = new HashSet<>(0);

	public Sede() {
	}

	public Sede(int idSede, String nomSede) {
		this.idSede = idSede;
		this.nomSede = nomSede;
	}

	public Sede(int idSede, String nomSede, Set<Departamento> departamentos, Set<ProyectoSede> proyectoSedes) {
		this.idSede = idSede;
		this.nomSede = nomSede;
		this.departamentos = departamentos;
		this.proyectoSedes = proyectoSedes;
	}

	public int getIdSede() {
		return this.idSede;
	}

	public void setIdSede(int idSede) {
		this.idSede = idSede;
	}

	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	public Set<ProyectoSede> getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

}
