package modelHibernate;
// Generated 4 mar 2025, 17:25:59 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idJugador;
	private String nombre;
	private Integer numeroCamiseta;
	private Set<Partidos> partidos = new HashSet<>(0);

	public Jugadores() {
	}

	public Jugadores(String nombre, Integer numeroCamiseta, Set<Partidos> partidos) {
		this.nombre = nombre;
		this.numeroCamiseta = numeroCamiseta;
		this.partidos = partidos;
	}

	public Integer getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(Integer idJugador) {
		this.idJugador = idJugador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getNumeroCamiseta() {
		return this.numeroCamiseta;
	}

	public void setNumeroCamiseta(Integer numeroCamiseta) {
		this.numeroCamiseta = numeroCamiseta;
	}

	public Set<Partidos> getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set<Partidos> partidos) {
		this.partidos = partidos;
	}
	
	public int partidosSize() {
		return this.partidos.size();
	}
}
