package modelHibernate;
// Generated 4 mar 2025, 17:25:59 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPartido;
	private Date fecha;
	private String lugar;
	private Set<Jugadores> jugadores = new HashSet<>(0);

	public Partidos() {
	}

	public Partidos(Date fecha, String lugar, Set<Jugadores> jugadores) {
		this.fecha = fecha;
		this.lugar = lugar;
		this.jugadores = jugadores;
	}

	public Integer getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(Integer idPartido) {
		this.idPartido = idPartido;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public Set<Jugadores> getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Set<Jugadores> jugadores) {
		this.jugadores = jugadores;
	}

}
