package com.pancetas.main.modelo;
// Generated 10 feb 2025, 10:59:04 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3982349301747550937L;
	private String dni;
	private String nomEmp;
	private Set<Proyecto> proyectosTrabaja = new HashSet<>(0);
	private Set<Proyecto> proyectosJefe = new HashSet<>(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set<Proyecto> proyectosTrabaja, Set<Proyecto> proyectosJefe) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectosTrabaja = proyectosTrabaja;
		this.proyectosJefe = proyectosJefe;
	}

	@Id

	@Column(name = "dni", unique = true, nullable = false, length = 9)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nom_emp", nullable = false, length = 40)
	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "asig_proyecto", joinColumns = {
			@JoinColumn(name = "dni_emp", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_proy", nullable = false) })
	public Set<Proyecto> getProyectosTrabaja() {
		return this.proyectosTrabaja;
	}

	public void setProyectosTrabaja(Set<Proyecto> proyectosTrabaja) {
		this.proyectosTrabaja = proyectosTrabaja;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "empleadoJefe")
	public Set<Proyecto> getProyectosJefe() {
		return this.proyectosJefe;
	}

	public void setProyectosJefe(Set<Proyecto> proyectosJefe) {
		this.proyectosJefe = proyectosJefe;
	}

	@Override
	public String toString() {
		return "Empleado [dni=" + dni + ", nomEmp=" + nomEmp + "]";
	}
	
	

}
