package com.pancetas.main.modelo;
// Generated 10 feb 2025, 10:59:04 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.JoinColumn;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto")
public class Proyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5465527657422930059L;
	private Integer idProy;
	private Empleado empleadoJefe;
	private String nomProy;
	private Set<Empleado> empleados = new HashSet<>(0);

	public Proyecto() {
	}

	public Proyecto(Empleado empleadoJefe, String nomProy) {
		this.empleadoJefe = empleadoJefe;
		this.nomProy = nomProy;
	}

	public Proyecto(Empleado empleadoJefe, String nomProy, Set<Empleado> empleados) {
		this.empleadoJefe = empleadoJefe;
		this.nomProy = nomProy;
		this.empleados = empleados;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_proy", unique = true, nullable = false)
	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni_jefe_proy", nullable = false)
	public Empleado getEmpleadoJefe() {
		return this.empleadoJefe;
	}

	public void setEmpleadoJefe(Empleado empleadoJefe) {
		this.empleadoJefe = empleadoJefe;
	}

	@Column(name = "nom_proy", nullable = false, length = 32)
	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "asig_proyecto", joinColumns = {
			@JoinColumn(name = "id_proy", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "dni_emp", nullable = false, updatable = false) })
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
