package modelo;
// Generated 10 feb 2025, 10:57:04 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

	private String dni;
	private String nomEmp;
	private Set proyectos = new HashSet(0);
	private Set proyectos_1 = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set proyectos, Set proyectos_1) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectos = proyectos;
		this.proyectos_1 = proyectos_1;
	}

	@Id

	@Column(name = "dni", unique = true, nullable = false, length = 9)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nom_emp", nullable = false, length = 40)
	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "asig_proyecto", joinColumns = {
			@JoinColumn(name = "dni_emp", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_proy", nullable = false, updatable = false) })
	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set getProyectos_1() {
		return this.proyectos_1;
	}

	public void setProyectos_1(Set proyectos_1) {
		this.proyectos_1 = proyectos_1;
	}

}
