package modelo;
// Generated 10 feb 2025, 10:57:04 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto")
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Empleado empleado;
	private String nomProy;
	private Set empleados = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(Empleado empleado, String nomProy) {
		this.empleado = empleado;
		this.nomProy = nomProy;
	}

	public Proyecto(Empleado empleado, String nomProy, Set empleados) {
		this.empleado = empleado;
		this.nomProy = nomProy;
		this.empleados = empleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_proy", unique = true, nullable = false)
	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni_jefe_proy", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "nom_proy", nullable = false, length = 32)
	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "asig_proyecto", joinColumns = {
			@JoinColumn(name = "id_proy", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "dni_emp", nullable = false, updatable = false) })
	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
