package modelo;

import jakarta.persistence.*;

// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final



/**
 * Accesos generated by hbm2java
 */
@Entity
@Table(name = "accesos")
public class Acceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codAcceso;
	private Estacion estacion;
	private String descripcion;

	public Acceso() {
	}

	public Acceso(Estacion estaciones, String descripcion) {
		this.estacion = estaciones;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codAcceso", unique = true, nullable = false)
	public Integer getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(Integer codAcceso) {
		this.codAcceso = codAcceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codEstacion", nullable = false)
	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
