package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Cocheras generated by hbm2java
 */
@Entity
@Table(name = "cocheras")
public class Cochera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codCochera;
	private String nombre;
	private String direccion;
	private Set<Tren> trenes = new HashSet<>(0);

	public Cochera() {
	}

	public Cochera(String nombre, String direccion) {
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public Cochera(String nombre, String direccion, Set<Tren> trenes) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.trenes = trenes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codCochera", unique = true, nullable = false)
	public Integer getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(Integer codCochera) {
		this.codCochera = codCochera;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cochera")
	public Set<Tren> getTrenes() {
		return this.trenes;
	}

	public void setTrenes(Set<Tren> trenes) {
		this.trenes = trenes;
	}

}
