package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;
/**
 * Estaciones generated by hbm2java
 */
@Entity
@Table(name = "estaciones")
public class Estacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codEstacion;
	private String nombre;
	private String direccion;
	private int numAccesos;
	private int numLineas;
	private int numViajesDestino;
	private int numViajesOrigen;
	private Set<LineaEstacion> lineasEstacion = new HashSet<>(0);
	private Set<Acceso> accesos = new HashSet<>(0);
	private Set<Viaje> viajesForEstacionDestino = new HashSet<>(0);
	private Set<Viaje> viajesForEstacionOrigen = new HashSet<>(0);

	public Estacion() {
	}

	public Estacion(String nombre, String direccion, int numAccesos, int numLineas, int numViajesDestino,
			int numViajesOrigen) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.numAccesos = numAccesos;
		this.numLineas = numLineas;
		this.numViajesDestino = numViajesDestino;
		this.numViajesOrigen = numViajesOrigen;
	}

	public Estacion(String nombre, String direccion, int numAccesos, int numLineas, int numViajesDestino,
			int numViajesOrigen, Set<LineaEstacion> lineasEstacion, Set<Acceso> accesos, Set<Viaje> viajesForEstacionDestino,
			Set<Viaje> viajesForEstacionOrigen) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.numAccesos = numAccesos;
		this.numLineas = numLineas;
		this.numViajesDestino = numViajesDestino;
		this.numViajesOrigen = numViajesOrigen;
		this.lineasEstacion = lineasEstacion;
		this.accesos = accesos;
		this.viajesForEstacionDestino = viajesForEstacionDestino;
		this.viajesForEstacionOrigen = viajesForEstacionOrigen;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codEstacion", unique = true, nullable = false)
	public Integer getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(Integer codEstacion) {
		this.codEstacion = codEstacion;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "numAccesos", nullable = false)
	public int getNumAccesos() {
		return this.numAccesos;
	}

	public void setNumAccesos(int numAccesos) {
		this.numAccesos = numAccesos;
	}

	@Column(name = "numLineas", nullable = false)
	public int getNumLineas() {
		return this.numLineas;
	}

	public void setNumLineas(int numLineas) {
		this.numLineas = numLineas;
	}

	@Column(name = "numViajesDestino", nullable = false)
	public int getNumViajesDestino() {
		return this.numViajesDestino;
	}

	public void setNumViajesDestino(int numViajesDestino) {
		this.numViajesDestino = numViajesDestino;
	}

	@Column(name = "numViajesOrigen", nullable = false)
	public int getNumViajesOrigen() {
		return this.numViajesOrigen;
	}

	public void setNumViajesOrigen(int numViajesOrigen) {
		this.numViajesOrigen = numViajesOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacion")
	public Set<LineaEstacion> getLineasEstacion() {
		return this.lineasEstacion;
	}

	public void setLineasEstacion(Set<LineaEstacion> lineasEstacion) {
		this.lineasEstacion = lineasEstacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacion")
	public Set<Acceso> getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set<Acceso> accesos) {
		this.accesos = accesos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacionDestino")
	public Set<Viaje> getViajesForEstacionDestino() {
		return this.viajesForEstacionDestino;
	}

	public void setViajesForEstacionDestino(Set<Viaje> viajesForEstacionDestino) {
		this.viajesForEstacionDestino = viajesForEstacionDestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacionOrigen")
	public Set<Viaje> getViajesForEstacionOrigen() {
		return this.viajesForEstacionOrigen;
	}

	public void setViajesForEstacionOrigen(Set<Viaje> viajesForEstacionOrigen) {
		this.viajesForEstacionOrigen = viajesForEstacionOrigen;
	}

}
