package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Lineas generated by hbm2java
 */
@Entity
@Table(name = "lineas")
public class Linea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codLinea;
	private String nombre;
	private Set<LineaEstacion> lineasEstacion = new HashSet<>(0);
	private Set<Tren> trenes = new HashSet<>(0);

	public Linea() {
	}

	public Linea(String nombre) {
		this.nombre = nombre;
	}

	public Linea(String nombre, Set<LineaEstacion> lineasEstacion, Set<Tren> trenes) {
		this.nombre = nombre;
		this.lineasEstacion = lineasEstacion;
		this.trenes = trenes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codLinea", unique = true, nullable = false)
	public Integer getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(Integer codLinea) {
		this.codLinea = codLinea;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linea")
	public Set<LineaEstacion> getLineasEstacion() {
		return this.lineasEstacion;
	}

	public void setLineasEstacion(Set<LineaEstacion> lineasEstacion) {
		this.lineasEstacion = lineasEstacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linea")
	public Set<Tren> getTrenes() {
		return this.trenes;
	}

	public void setTrenes(Set<Tren> trenes) {
		this.trenes = trenes;
	}

	@Override
	public String toString() {
		return "Linea: " + codLinea + " - " + nombre;
	}
	
	

}
