package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import jakarta.persistence.*;
/**
 * Lineaestacion generated by hbm2java
 */
@Entity
@Table(name = "lineaestacion")
public class LineaEstacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LineaEstacionId id;
	private Estacion estacion;
	private Linea linea;
	private int orden;

	public LineaEstacion() {
	}

	public LineaEstacion(LineaEstacionId id, Estacion estacion, Linea linea, int orden) {
		this.id = id;
		this.estacion = estacion;
		this.linea = linea;
		this.orden = orden;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codLinea", column = @Column(name = "codLinea", nullable = false)),
			@AttributeOverride(name = "codEstacion", column = @Column(name = "codEstacion", nullable = false)) })
	public LineaEstacionId getId() {
		return this.id;
	}

	public void setId(LineaEstacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codEstacion", nullable = false, insertable = false, updatable = false)
	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codLinea", nullable = false, insertable = false, updatable = false)
	public Linea getLinea() {
		return this.linea;
	}

	public void setLinea(Linea linea) {
		this.linea = linea;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
