package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import jakarta.persistence.*;
/**
 * Trenes generated by hbm2java
 */
@Entity
@Table(name = "trenes")
public class Tren implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codTren;
	private Linea linea;
	private Cochera cochera;
	private String nombre;
	private String tipo;

	public Tren() {
	}

	public Tren(Linea linea, Cochera cochera, String nombre, String tipo) {
		this.linea = linea;
		this.cochera = cochera;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codTren", unique = true, nullable = false)
	public Integer getCodTren() {
		return this.codTren;
	}

	public void setCodTren(Integer codTren) {
		this.codTren = codTren;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codLinea", nullable = false)
	public Linea getLinea() {
		return this.linea;
	}

	public void setLinea(Linea linea) {
		this.linea = linea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codCochera", nullable = false)
	public Cochera getCochera() {
		return this.cochera;
	}

	public void setCochera(Cochera cochera) {
		this.cochera = cochera;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo", nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
