package modelo;
// Generated 7 feb 2025, 8:57:11 by Hibernate Tools 3.6.2.Final

import jakarta.persistence.*;
/**
 * Viajes generated by hbm2java
 */
@Entity
@Table(name = "viajes")
public class Viaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codViaje;
	private Estacion estacionDestino;
	private Estacion estacionOrigen;
	private String nombre;

	public Viaje() {
	}

	public Viaje(Estacion estacionDestino, Estacion estacionOrigen, String nombre) {
		this.estacionDestino = estacionDestino;
		this.estacionOrigen = estacionOrigen;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "codViaje", unique = true, nullable = false)
	public Integer getCodViaje() {
		return this.codViaje;
	}

	public void setCodViaje(Integer codViaje) {
		this.codViaje = codViaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estacionDestino", nullable = false)
	public Estacion getEstacionDestino() {
		return this.estacionDestino;
	}

	public void setEstacionDestino(Estacion estacionDestino) {
		this.estacionDestino = estacionDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estacionOrigen", nullable = false)
	public Estacion getEstacionOrigen() {
		return this.estacionOrigen;
	}

	public void setEstacionOrigen(Estacion estacionOrigen) {
		this.estacionOrigen = estacionOrigen;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
