package beans;
// Generated 17 ene 2025, 19:23:50 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private String nomEmp;
	private Set<Proyecto> proyectosTrabaja = new HashSet<>(0);
	private Set<Proyecto> proyectosJefe = new HashSet<>(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set<Proyecto> proyectosTrabaja, Set<Proyecto> proyectosJefe) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectosTrabaja = proyectosTrabaja;
		this.proyectosJefe = proyectosJefe;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public Set<Proyecto> getProyectosTrabaja() {
		return this.proyectosTrabaja;
	}

	public void setProyectosTrabaja(Set<Proyecto> proyectosTrabaja) {
		this.proyectosTrabaja = proyectosTrabaja;
	}

	public Set<Proyecto> getProyectosJefe() {
		return this.proyectosJefe;
	}

	public void setProyectosJefe(Set<Proyecto> proyectosJefe) {
		this.proyectosJefe = proyectosJefe;
	}

	@Override
	public String toString() {
		return "Empleado [dni= " + dni + ", nomEmp= " + nomEmp + "]";
	}

}
