package beans;
// Generated 17 ene 2025, 19:23:50 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private String nomEmp;
	private Set<Proyecto> proyectosEnLosQueEstaInvolucrado = new HashSet<>(0);
	private Set<Proyecto> proyectosInvolucradosEnLosQueEsJefe = new HashSet<>(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set<Proyecto> proyectos, Set<Proyecto> proyectos_1) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectosEnLosQueEstaInvolucrado = proyectos;
		this.proyectosInvolucradosEnLosQueEsJefe = proyectos_1;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public Set<Proyecto> getProyectos() {
		return this.proyectosEnLosQueEstaInvolucrado;
	}

	public void setProyectos(Set<Proyecto> proyectos) {
		this.proyectosEnLosQueEstaInvolucrado = proyectos;
	}

	public Set<Proyecto> getProyectos_1() {
		return this.proyectosInvolucradosEnLosQueEsJefe;
	}

	public void setProyectos_1(Set<Proyecto> proyectos_1) {
		this.proyectosInvolucradosEnLosQueEsJefe = proyectos_1;
	}

	@Override
	public String toString() {
		return "Empleado [dni= " + dni + ", nomEmp= " + nomEmp + "]";
	}

}
