package beans;

import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Empleado empleadoJefe;
	private String nomProy;
	private Set<Empleado> empleados = new HashSet<>(0);

	public Proyecto() {
	}

	public Proyecto(Empleado empleado, String nomProy) {
		this.empleadoJefe = empleado;
		this.nomProy = nomProy;
	}

	public Proyecto(Empleado empleadoJefe, String nomProy, Set<Empleado> empleados) {
		this.empleadoJefe = empleadoJefe;
		this.nomProy = nomProy;
		this.empleados = empleados;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Empleado getEmpleadoJefe() {
		return this.empleadoJefe;
	}

	public void setEmpleadoJefe(Empleado empleadoJefe) {
		this.empleadoJefe = empleadoJefe;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@Override
	public String toString() {
		return "Proyecto [idProy=" + idProy + ", empleadoJefe=" + empleadoJefe + ", nomProy=" + nomProy + "]";
	}

	
}
