package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDepto;
	private Sede sede;
	private String nomDepto;
	private Set<Empleado> empleados = new HashSet<>(0);

	public Departamento() {
	}

	public Departamento(Sede sede, String nomDepto) {
		this.sede = sede;
		this.nomDepto = nomDepto;
	}

	public Departamento(Sede sede, String nomDepto, Set<Empleado> empleados) {
		this.sede = sede;
		this.nomDepto = nomDepto;
		this.empleados = empleados;
	}

	public Integer getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(Integer idDepto) {
		this.idDepto = idDepto;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public String getNomDepto() {
		return this.nomDepto;
	}

	public void setNomDepto(String nomDepto) {
		this.nomDepto = nomDepto;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
