package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private Departamento departamento;
	private String nomEmp;
	private EmpleadoDatosProf empleadoDatosProf;

	public Empleado() {
	}

	public Empleado(String dni, Departamento departamento, String nomEmp) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, Departamento departamento, String nomEmp, EmpleadoDatosProf empleadoDatosProf) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
		this.empleadoDatosProf = empleadoDatosProf;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public EmpleadoDatosProf getEmpleadoDatosProf() {
		return this.empleadoDatosProf;
	}

	public void setEmpleadoDatosProf(EmpleadoDatosProf empleadoDatosProf) {
		this.empleadoDatosProf = empleadoDatosProf;
	}

}
