package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * EmpleadoDatosProf generated by hbm2java
 */
@Entity
@Table(name = "empleado_datos_prof")
public class EmpleadoDatosProf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private Empleado empleado;
	private String categoria;
	private BigDecimal sueldoBrutoAnual;

	public EmpleadoDatosProf() {
	}

	public EmpleadoDatosProf(Empleado empleado, String categoria) {
		this.empleado = empleado;
		this.categoria = categoria;
	}

	public EmpleadoDatosProf(Empleado empleado, String categoria, BigDecimal sueldoBrutoAnual) {
		this.empleado = empleado;
		this.categoria = categoria;
		this.sueldoBrutoAnual = sueldoBrutoAnual;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public BigDecimal getSueldoBrutoAnual() {
		return this.sueldoBrutoAnual;
	}

	public void setSueldoBrutoAnual(BigDecimal sueldoBrutoAnual) {
		this.sueldoBrutoAnual = sueldoBrutoAnual;
	}

}
