package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * ProyectoSede generated by hbm2java
 */
@Entity
@Table(name = "proyecto_sede")
public class ProyectoSede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
//	private ProyectoSedeId id;
//	private Proyecto proyecto;
//	private Sede sede;
//	private Date FInicio;
//	private Date FFin;
	

	@EmbeddedId
	private ProyectoSedeId id;

	@ManyToOne
	@JoinColumn(name = "id_proy", insertable = false, updatable = false)
	private Proyecto proyecto;

	@ManyToOne
	@JoinColumn(name = "id_sede", insertable = false, updatable = false)
	private Sede sede;

	@Column(name = "f_inicio")
	private Date FInicio;

	@Column(name = "f_fin")
	private Date FFin;

	public ProyectoSede() {
	}

	public ProyectoSede(ProyectoSedeId id, Proyecto proyecto, Sede sede, Date FInicio) {
		this.id = id;
		this.proyecto = proyecto;
		this.sede = sede;
		this.FInicio = FInicio;
	}

	public ProyectoSede(ProyectoSedeId id, Proyecto proyecto, Sede sede, Date FInicio, Date FFin) {
		this.id = id;
		this.proyecto = proyecto;
		this.sede = sede;
		this.FInicio = FInicio;
		this.FFin = FFin;
	}

	public ProyectoSedeId getId() {
		return this.id;
	}

	public void setId(ProyectoSedeId id) {
		this.id = id;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public Date getFInicio() {
		return this.FInicio;
	}

	public void setFInicio(Date FInicio) {
		this.FInicio = FInicio;
	}

	public Date getFFin() {
		return this.FFin;
	}

	public void setFFin(Date FFin) {
		this.FFin = FFin;
	}

}
