package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto")
public class Proyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProy;
	private Date FInicio;
	private Date FFin;
	private String nomProy;
	private Set<ProyectoSede> proyectoSedes = new HashSet<>(0);

	public Proyecto() {
	}

	public Proyecto(Date FInicio, String nomProy) {
		this.FInicio = FInicio;
		this.nomProy = nomProy;
	}

	public Proyecto(Date FInicio, Date FFin, String nomProy, Set<ProyectoSede> proyectoSedes) {
		this.FInicio = FInicio;
		this.FFin = FFin;
		this.nomProy = nomProy;
		this.proyectoSedes = proyectoSedes;
	}
	
	public Proyecto(Date fInicio, Date fFin, String nomProy) {
		super();
		FInicio = fInicio;
		FFin = fFin;
		this.nomProy = nomProy;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Date getFInicio() {
		return this.FInicio;
	}

	public void setFInicio(Date FInicio) {
		this.FInicio = FInicio;
	}

	public Date getFFin() {
		return this.FFin;
	}

	public void setFFin(Date FFin) {
		this.FFin = FFin;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set<ProyectoSede> getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

}
