package beans;
// Generated 18 ene 2025, 17:26:25 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede")
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSede;
	private String nomSede;
	private Set<Departamento> departamentos = new HashSet<>(0);
	private Set<ProyectoSede> proyectoSedes = new HashSet<>(0);

	public Sede() {
	}

	public Sede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Sede(String nomSede, Set<Departamento> departamentos, Set<ProyectoSede> proyectoSedes) {
		this.nomSede = nomSede;
		this.departamentos = departamentos;
		this.proyectoSedes = proyectoSedes;
	}

	public Integer getIdSede() {
		return this.idSede;
	}

	public void setIdSede(Integer idSede) {
		this.idSede = idSede;
	}

	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	public Set<ProyectoSede> getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

}
